[package]
name = "annotator"
version = "0.1.0"
edition = "2021"
authors = ["Ryan Ruckley <rruckley@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.9.0"
reqwest = "0.11.16"
serde = "1.0.159"
tokio = "1.27.0"
